### ISSUE TITLE
When I do a build from humble - file permissions error

### ISSUE THREAD

**Issue by brianlmerritt** [atinfinity/l4t-ros2-docker#1]
On Orin Nano build I get the following error

RUN rm /usr/share/glvnd/egl_vendor.d/50_mesa.json &&     mkdir -p /usr/share/glvnd/egl_vendor.d/ && echo '{    "file_format_version" : "1.0.0",    "ICD" : {        "library_path" : "libEGL_nvidia.so.0"    }}' > /usr/share/glvnd/egl_vendor.d/10_nvidia.json
 ---> Running in 87fac5429da1
/bin/sh: 1: cannot create /usr/share/glvnd/egl_vendor.d/10_nvidia.json: Read-only file system

Am I $USERNAME in the build in this part?  If so does it need SUDO equivalent?

**Comment by brianlmerritt** [comment]
No, not sudo issue.  Something to do with creating the file.

I changed code to below and it works fine on Orin Nano.  Tested also on old Nano 4GB without the change and it seems fine.
```
RUN rm -rf /usr/share/glvnd/egl_vendor.d && \
     mkdir -p /usr/share/glvnd/egl_vendor.d/ && echo '\
{\
    "file_format_version" : "1.0.0",\
    "ICD" : {\
        "library_path" : "libEGL_nvidia.so.0"\
    }\
}' > /usr/share/glvnd/egl_vendor.d/10_nvidia.json
```

**Comment by atinfinity** [comment]
@brianlmerritt Thank you for your feedback. I refered to the following Dockerfile.
<https://gitlab.com/nvidia/container-images/l4t-base/-/blob/170c6b5c1b0007fdaf0893e5e65e56e568845102/Dockerfile.l4t_r34#L69-76>

And, there is `/usr/share/glvnd/egl_vendor.d/10_nvidia.json` in Jetson Orin NX.
It seems that this setting more appropriate. So, I'll update Dockerfile.

**Comment by atinfinity** [comment]
I resolved this problem in <https://github.com/atinfinity/l4t-ros2-docker/pull/2>. So, I closed this issue.
