### ISSUE TITLE
Orin Nano now has permission issues with /home/jetson on container.

### ISSUE THREAD

**Issue by brianlmerritt** [atinfinity/l4t-ros2-docker#3]
Very weird, but on Orin Nano I am now getting a build error:

```
Step 26/28 : RUN echo "export PATH=/usr/local/cuda/bin:$PATH" >> ~/.bashrc &&     echo "export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH" >> ~/.bashrc
 ---> Running in e770f7d461d5
/bin/bash: /home/jetson/.bash_profile: Permission denied
/bin/bash: line 1: /home/jetson/.bashrc: Permission denied
```

Further investigation reveals the /home/jetson directory is still owned by root, and the .bashrc files too

I re-imaged today with latest jetpack, but still getting the same issues.

I did not get this error on Jetson Nano 4GB (and /home/jetson permissions were ok) and it also worked on Orin Dev but I haven't had chance to try recently.

*May* be related to imaging technique - I set username and password in the sdkmanager rather than do a manual install where I need to dig out screen & keyboard & mouse and enter username on device.

**Comment by atinfinity** [comment]
@brianlmerritt I think that this is a bug of Docker Engine.
<https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/2029564>

I downgraded to Docker Engine 20.10.21.
As a result, I could avoid this issue.

**Comment by brianlmerritt** [comment]
Good spot! Thanks!

**Comment by brianlmerritt** [comment]
ps - If I get a chance I will try upgrade docker.io to https://launchpad.net/ubuntu/+source/docker.io-app/24.0.5-0ubuntu1/+build/26516988/+files/docker.io_24.0.5-0ubuntu1_arm64.deb
