### ISSUE TITLE
Is sudo capability needed?

### ISSUE THREAD

**Issue by brianlmerritt** [atinfinity/l4t-ros2-docker#4]
Sorry to trouble you again, but is the ability to do sudo without password used for anything?

I have a fork and can remove myself, but was wondering if you have a specific use case or not.

Thanks if you have time to answer :D

**Comment by atinfinity** [comment]
@brianlmerritt In general, user should set a password for your account. I assumed that user uses this Dockerfile to build the development environment for prototype. So, it is structured this way to simplify the procedure. I' ll update at a later date.

**Comment by brianlmerritt** [comment]
Not a problem, just interested.
